Первая попытка сдать
P1r0g/java-kanban pull request #2
Opened 2024-06-18 15:42 UTC by P1r0g

Реализованы все методы из ТЗ, работает без ошибок

2024-06-19 12:47 UTC, ErkinKasymaliev requested changes
привет!
из ТЗ:
"
Удалите задачу, которая есть в истории, и проверьте, что при печати она не будет выводиться.
Удалите эпик с тремя подзадачами и убедитесь, что из истории удалился как сам эпик, так и все его подзадачи.
"
при удалении тасков, они остаются в истории, а должны удаляться

2024-06-25 05:50 UTC, ErkinKasymaliev requested changes
привет, оставил коммент

2024-06-25 05:50 UTC, ErkinKasymaliev commented on src/service/InMemoryTaskManager.java
> +        for (Epic epic : epics.values()) {
здесь и в методах deleteAllTasks и deleteAllSubtasks у вас кидает ошибку?
сделайте так:
```
for (Epic epic : epics.values()) {
   for (SubTask subTask : epic.getSubTasks()) {
       historyManager.remove(subTask.getId());
    }
     historyManager.remove(epic.getId());
}
subtask.clear();
epics.clear();
```

аналогично в 2х других методах

2024-07-19 13:21 UTC, ErkinKasymaliev requested changes
привет, у вас тесты не прошли в git-е, без зеленой сборки работу принять не могу

2024-07-20 12:27 UTC, P1r0g commented
У меня выдает ошибку на тесте, где идет проверка на то, что эпики нельзя добавить в список подзадач внутри себя, но у меня в сигнатуре метода стоит, что можно добавить только SubTask, то есть эпики сразу отметаются и как решить эту проблему я не понимаю.

Возможно ли глянуть код теста, что бы понять как именно происходит это добавление и предотвращать его?

2024-07-21 06:52 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-07-21 09:43 UTC, merged