Реализация тз
P1r0g/java-kanban pull request #4
Opened 2024-12-07 18:37 UTC by P1r0g

2024-12-08 23:00 UTC, P1r0g commented
Нужна помощь, очень сильно не понимаю почему он у меня не записывает duration, startTime в файл у Epica, уже неделю с этим борюсь и никак не могу решить эту проблему.

2024-12-09 08:14 UTC, ErkinKasymaliev requested changes
привет!
1) оставил коммент
2) почините тесты
3) добавьте тесты на успешное добавления задания, на пересечение при добавление задач, на prioritizedTasks

2024-12-09 08:14 UTC, ErkinKasymaliev commented on src/model/Epic.java
> +        return getStartTime().plus(getDuration());
для эпика так endTime не рассчитывается, вы его должны рассчитать endTime последнего сабтаска и засеттить. Из ТЗ: "Для реализации getEndTime() удобно добавить поле endTime в Epic и рассчитать его вместе с другими полями."

2024-12-11 10:51 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-12-11 11:08 UTC, merged